---

language: node_js

cache: yarn

node_js:
  - lts/*
  - stable

cache: yarn

before_script:
  - yarn global add coveralls

script:
  - npm run testcov

after_success:
  - npm run --silent lcov | coveralls
